config/routes.rb
Rails.application.routes.draw do
  
  
  root 'pages#index'
  get '/mision-vision', to: "pages#mision_vision"
  get '/valores', to: "pages#valores"
  get '/organigrama', to: "pages#organigrama"
  get '/macroproceso', to: "pages#macroproceso"
  get '/cadena-valor', to: "pages#cadena"
  get '/fuerzas-porter', to: "pages#fuerzas"
  get '/factores-internos', to: "pages#factor_interno"
  get '/factores-externos', to: "pages#factor_externo"
  get '/matriz-foda', to: "pages#matriz_foda"
  get '/mapa-estrategico', to: "pages#mapa_estrategico"
  get '/indicador-datos', to: "pages#indicador_datos"
  get '/indicador-maestro', to: "pages#indicador_maestro"
  get '/indicador-resumen', to: "pages#indicador_resumen"


  devise_for :users
  resources :informations, :values, :areas, :activities, :forces, :factors, :expect => [:show] 
  resources :strategies, :expect => [:create]
  resources :perspectives, only: [:edit, :update, :new, :create]
  resources :objectives, :expect => [:show, :new, :edit]
  resources :procesos, :expect => [:update, :show] 
  resources :datos 
  resources :indicators, :fichas, :expect => [:new, :edit]
  
  get '/organigrama-empresa', to: 'informations#organigrama', as: 'organigrama_empresa'

  put '/procesos/:id', to: 'procesos#update', as: 'update_proceso'

  get '/subproceso/new/:proceso_id', to: 'subprocesos#new', as: 'new_subproceso'
  get '/subproceso/:proceso_id/edit/:id', to: 'subprocesos#edit', as: 'edit_subproceso'
  post '/subprocesos', to: 'subprocesos#create', as: 'create_subproceso'
  put '/subprocesos/:id', to: 'subprocesos#update', as: 'update_subproceso'
  delete '/subprocesos/:id', to: 'subprocesos#destroy', as: 'destroy_subproceso'
   
  get '/nueva-actividad/:area_id', to: "activities#new_actividad", as: 'actividad'
  get '/editar-actividad/:id/:area_id', to: 'activities#edit_actividad', as: 'actividad_edit'
  get '/nuevo-factor/:force_id', to: "factors#new_factor", as: 'factor_new'
  get '/editar-factor/:id/:force_id', to: 'factors#edit_factor', as: 'factor_edit'

  get '/evaluar-factor-interno', to: "evaluations#evaluar_factor_interno", as: 'evaluar_factor_interno'
  get '/edit-factor-interno/:id', to: "evaluations#edit_factor_interno", as: 'edit_factor_interno'
  put '/update-factor-interno/:id', to: 'activities#update_factor_interno', as: 'update_factor_interno'
  get '/evaluar-factor-externo', to: "evaluations#evaluar_factor_externo", as: 'evaluar_factor_externo'
  get '/edit-factor-externo/:id', to: "evaluations#edit_factor_externo", as: 'edit_factor_externo'
  put '/update-factor-externo/:id', to: 'factors#update_factor_externo', as: 'update_factor_externo'

  get '/strategies/new/:tipo', to: 'strategies#new', as: 'strategy_new'

  get '/nuevo-objective/:perspective_id', to: "objectives#new", as: 'objective_new'
  get '/editar-objective/:id/:perspective_id', to: 'objectives#edit', as: 'objective_edit'

  get '/mapa-estrategico-relaciones', to: "objectives#mapa", as: 'mapa_estrategico_relaciones'

  get '/nuevo-indicador/:objective_id', to: "indicators#new", as: 'indicator_new'
  get '/editar-indicador/:id/:objective_id', to: 'indicators#edit', as: 'indicator_edit'
  
  get '/nuevo-dato/:indicator_id', to: "datos#new", as: 'dato_new'
  get '/editar-dato/:id/:indicator_id', to: 'datos#edit', as: 'dato_edit'

  get '/nuevo-ficha/:indicator_id', to: "fichas#new", as: 'ficha_new'
  get '/editar-ficha/:id/:indicator_id', to: 'fichas#edit', as: 'ficha_edit'
  
  get '/maestro', to: 'maestro#index', as: 'maestro'
  get '/resumen', to: 'maestro#resumen', as: 'resumen'

end

app/models/objective.rb
# == Schema Information
#
# Table name: objectives
#
#  id             :bigint(8)        not null, primary key
#  content        :text(65535)
#  slug           :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  perspective_id :bigint(8)
#
# Indexes
#
#  index_objectives_on_perspective_id  (perspective_id)
#
# Foreign Keys
#
#  fk_rails_...  (perspective_id => perspectives.id)
#

class Objective < ApplicationRecord 
  validates :content, presence: true, length: {minimum:10}
  
  belongs_to :perspective

  has_many :indicators, dependent: :destroy

  scope :perspectiva, -> (perspective_id) { where perspective_id: perspective_id }
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController
    before_action :authenticate_user!
    before_action :find_objective, only: [:edit, :update, :show, :destroy]


    def index
        @perspectives = Perspective.all
    end


    def show
    end


    def new
        @perspective_id = params[:perspective_id]
        @estrategias = Strategy.all
        @objective = Objective.new
    end


    def edit
        @estrategia = []
        @objective = Objective.find(params[:id])
        @my_estrategies = InObjective::where(objective_id: @objective[:id])
    end

    def mapa
        @perspectives = Perspective.all
    end
    

    def create
        @perspective = Perspective.find(params[:objective][:perspective_id])
        @count = Objective.where(perspective_id: params[:objective][:perspective_id]).count
        @objective = Objective.new
        @objective[:slug] = @perspective[:slug]<<"#{@count + 1}" 
        @objective[:content] = params[:objective][:content]
        @objective[:perspective_id] = params[:objective][:perspective_id]

        @estrategias = params[:strategies]  
           
        respond_to do |format|
        if @objective.save

            @estrategias.each do |estrategia|
                @in_objective = InObjective.new
                @in_objective[:objective_id] = @objective[:id]
                @in_objective[:strategy_id] = estrategia[:id]
                if @in_objective.save
                    format.html { redirect_to objectives_url, notice: 'El objetivo fue creada con exitó.' }
                    format.json { redirect_to @objective, status: :created, location: @objective }
                else
                    format.json { render json: @in_objective.errors, status: :unprocessable_entity }
                end
                
            end
            
        else
            format.html { redirect_to objective_new_url(params[:objective][:perspective_id]), alert: 'Error al crear el objetivo.' }
            format.json { render json: @objective.errors, status: :unprocessable_entity }
        end
        end
    end


    def update
        @objective[:content] = params[:objective][:content]
        @estrategias =  params[:objective][:estrategias]  
        respond_to do |format|
        if @objective.save

            @in_objective = InObjective.new
            
            @estrategias.split(",").each do |slug|
                @in_objective[:objective_id] = @objective[:id]
                @estrategia = Strategy.where(slug: slug).first
                @in_objective[:strategy_id] = @estrategia[:id]
                @in_objective.save
            end            

            format.html { redirect_to objectives_url, notice: 'El objetivo fue editada con exitó.' }
            format.json { redirect_to @objective, status: :ok, location: @objective }
        else
            format.html { render :edit, perspective_id: params[:objective][:perspective_id] }
            format.json { render json: @objective.errors, status: :unprocessable_entity }
        end
        end
    end


    def destroy
        @objective.destroy
        respond_to do |format|
        format.html { redirect_to objectives_url, notice: 'El objetivo fue eliminada con exitó.' }
        format.json { head :no_content }
        end
    end

    private
        def objective_params
            params.require(:objective).permit(:content, :perspective_id)
        end

        def find_objective
            @objective = Objective.find(params[:id])
        end
end

app/helpers/objectives_helper.rb
module ObjectivesHelper
end

app/views/objectives/_form.html.erb
<%= form_with(model: objective, local: true) do |form| %>
  <% if objective.errors.any? %>
    <div class="message is-danger">
      <h2 class="title is-5"><%= pluralize(objective.errors.count, "error") %> al realizar la operación:</h2>
      <div class="message-body">
        <ul>
          <% objective.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content, class: "label is-normal" %>
    <div class="control"> 
      <%= form.text_field :content, class: "input is-info" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :estrategias, class: "label is-normal" %>
    <div class="control"> 
      <input class="input is-info" value="<%= estrategias.map{ |estrategia| estrategia.strategy.slug }.join(",") %>" type="text" name="objective[estrategias]" id="objective_estrategias">
    </div>
  </div>
  <div class="actifield is-grouped margin-small-topons">
    <%= form.submit "Editar", class: "button is-primary" %>
  </div>
<% end %>

app/views/objectives/edit.html.erb
<% @title = "Editar Objetivo" %>
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li> <%= link_to  "Objetivos", objectives_path %></li>
    <li class="is-active">      
      <a href="#" aria-current="page">Editar Objetivo</a>
    </li>
  </ul>
</nav>


<div class="columns">
  <div class="column is-half is-offset-one-quarter">
      <div class="card margin-small">
        <div class="card-content">
          <p class="title is-4 has-text-centered">Editar Objetivo</p>
          <p class="subtitle is-6 has-text-centered">Editar el objetivo del mapa estrategico.</p>
                      
          <%= render 'form', objective: @objective, estrategias: @my_estrategies %>

          <%= link_to 'Regresar', objectives_path %>
      </div>
  </div> 

  
</div>

app/views/objectives/index.html.erb
<% @title = "Objetivos Estratégicos" %>

<div class="columns">
  <div class="column">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li> <%= link_to  "Dashboard", root_path %></li>
        <li class="is-active">      
          <a href="#" aria-current="page">Objetivos Estratégicos</a>
        </li>
      </ul>
    </nav>
  </div>
  <div class="column is-flex-row-end">
    <%= link_to mapa_estrategico_relaciones_path, class: "button is-info" do %>
      <p> Mapa estratégico </p>
      <span class="icon">
          <i class="mdi mdi-arrow-right"></i>
      </span>
    <% end %>
    <%= link_to indicators_path, class: "ml-10 button is-info" do %>
      <p> Indicatores </p>
      <span class="icon">
          <i class="mdi mdi-arrow-right"></i>
      </span>
    <% end %>
  </div>
</div>


<div class="columns">
  <div class="column">
      <div class="card margin-small shadow-cm">
        <div class="card-content">
          <p class="subtitle has-text-centered">Las perspectivas y objetivos del mapa estratégico.</p>
          <div class="is-between">
            <p class="title is-4">Perspectivas y Objetivos Estratégicos</p>
            <%= link_to new_perspective_path, class: "button is-success" do %>
                <span class="icon">
                  <i class="mdi mdi-library-plus"></i>
                </span>
                <span><%= t('.new_perspective_link') %> </span>
            <% end %>
          </div>

          <div class="shadow-cm padding-small-all">
            <% @perspectives.each do |perspective| %>
              <div class="columns">
                <div class="column is-8 has-background-primary ">
                  <div class="has-text-white title is-5 has-text-weight-bold">
                    Perspectiva "<%= perspective.title %>"
                  </div>
                </div>

                <div class="column is-2 has-text-right has-background-primary has-text-white">
                  <span data-label="<%= t('.edit_perspective_link') %>" class="is-black is-top is-medium tooltip">
                    <%= link_to edit_perspective_path(perspective), class: "button is-info" do %>
                        <span class="icon">
                          <i class="mdi mdi-update"></i>
                        </span>
                    <% end %>
                  </span>
                  <span data-label="<%= t('.remove_perspective_link') %>" class="is-black is-top is-medium tooltip">
                    <%= link_to perspective_url(perspective), method: :delete, class: "button is-danger", data: {confirm: "¿Está seguro de eliminar la perspectiva?"} do %>
                        <span class="icon">
                          <i class="mdi mdi-close"></i>
                        </span>
                    <% end %>
                  </span>
                </div>

                <div class="column has-background-grey has-text-white">
                  <%= link_to objective_new_path(perspective), class: "button" do %>
                    <span class="icon">
                      <i class="mdi mdi-library-plus"></i>
                    </span>
                    <span><%= t('.new_link') %> </span>
                  <% end %>
                </div>
              </div>


              <% perspective.objectives.each do |objective| %>
                <div class="columns">
                    <div class="column is-1 has-text-centered has-text-weight-bold">
                      <%= objective.slug %>
                    </div>
                    <div class="column is-9 ">
                      <%= objective.content %>
                    </div>

                    <div class="column">
                      <span data-label="<%= t('.edit_link') %>" class="is-black is-top is-medium tooltip">
                        <%= link_to objective_edit_path(objective,perspective), class: "button is-info" do %>
                          <span class="icon">
                            <i class="mdi mdi-update"></i>
                          </span>
                        <% end %>
                      </span>
                      <span data-label="<%= t('.remove_link') %>" class="is-black is-top is-medium tooltip">
                        <%= link_to objective_url(objective), method: :delete,  class: "button is-danger", :data => {confirm: '¿Está seguro de eliminar la objective?'} do %>
                          <span class="icon">
                            <i class="mdi mdi-close"></i>
                          </span>
                        <% end %>
                      </span>
                    </div>
                </div>
              <% end %>
            <% end %>

          </div>

          


        </div>
      </div>

  </div>
</div>

app/views/objectives/mapa.html.erb
<% @title = "Objetivos Estratégicos" %>

<div class="columns">
  <div class="column">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li> <%= link_to  "Dashboard", root_path %></li>
        <li> <%= link_to  "Objetivos Estratégicos", objectives_path %></li>
        <li class="is-active">      
          <a href="#" aria-current="page">Mapa Estratégicos</a>
        </li>
      </ul>
    </nav>
  </div>
  <div class="column is-flex-row-end">
    <%= link_to indicators_path, class: "button is-info" do %>
    <p> Indicatores </p>
    <span class="icon">
        <i class="mdi mdi-arrow-right"></i>
    </span>
    <% end %>
  </div>
</div>



<div class="columns">
  <div class="column">
      <div class="card margin-small shadow-cm">
        <div class="card-content">
          <p class="title is-4 has-text-centered">Mapa Estratégicos.</p>           
 
          <div class="margin-small-top">
            <div class="columns">
              <div class="column is-3">
                <div class="title is-5">Perspectivas</div>
              </div>
              <div class="column">
                <div class="title is-5">Objetivos Estratégicos</div>
              </div>
            </div>


            <% @perspectives.each do |perspective| %>           
            <div class="columns">
              <div class="column is-3">
                  <div class="notification is-primary">
                      <%= perspective.title %>
                  </div>
              </div>

              <div class="column">
                  <div class="columns is-multiline">
                    <% perspective.objectives.each do |objective| %>
                    <div class="column is-4">
                        <div class="notification is-success">
                          <div class="columns">
                            <div class="column is-2">
                              <%= objective.slug %>
                            </div>
                            <div class="column">
                              <%= objective.content %>
                            </div>
                          </div>
                        </div>
                    </div>
                    <% end %>
                  </div>                 
              </div>
            </div>
              
            <% end %>

          </div>
        </div>
      </div>

  </div>
</div>

app/views/objectives/new.html.erb
<% @title = "Agregar Objetivo" %>
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li> <%= link_to  "Objetivos", objectives_path %></li>
    <li class="is-active">      
      <a href="#" aria-current="page">Agregar Objetivo</a>
    </li>
  </ul>
</nav>


<div class="columns">
  <div class="column is-half is-offset-one-quarter">
      <div class="card margin-small">
        <div class="card-content">
          <p class="title is-4 has-text-centered">Agregar objetivo</p>
          <p class="subtitle is-6 has-text-centered">Nueva objetivo del mapa estrategico.</p>
            <!--<form-objective 
              :editar="false" 
              :perspective_id="<%#=  @perspective_id.to_json %>"
              :id="<%#=  @objective.id.to_json %>"
              :estrategias="<%#= @estrategias.to_json(except: [:created_at, :updated_at]) %>"
              :objectivo="<%#= @objective.to_json(except: [:created_at, :updated_at, :perspective_id]) %>" 
               /> -->

            <%= content_tag :div,
                id: "add_form_objectivo",
                data: {
                    perspective: @perspective_id,
                    estrategias: @estrategias.to_json(except: [:created_at, :updated_at]),
                    objectivo: @objective.to_json(except: [:created_at, :updated_at, :perspective_id])
                } do %>

                <form @submit.prevent="submit">
                  <div class="field">
                      <label for="content" class="label is-normal">Objetivo</label>
                      
                      <div class="control">
                          <textarea id="content" v-model="objective.content" cols="10" rows="5" class="textarea is-info"></textarea>    
                          <div class="notification is-danger" v-if="errors.length > 0">                                                                                                        
                              <p v-for="(error, index) in errors" :key="index">El objetivo {{error}}</p>                                                       
                          </div> 
                      </div>
                  </div>
                  <b-field label="Asignar estrategias">
                      <b-taginput
                          v-model="strategies"
                          :data="filteredTags"
                          autocomplete
                          field="slug"
                          icon="label"
                          placeholder="Agregar Estrategia"
                          @typing="getFilteredTags">
                      </b-taginput>
                  </b-field>
                  <pre>{{strategies}}</pre>
                  <div class="field is-grouped margin-small-topons">
                      <button type="submit" class="button is-success">Guardar</button>            
                  </div>
                  <!--<a href="#" class="link link-info" @click.prevent="back()">Regresar</a>-->
                </form>

              <% end %>
           
            <%= link_to 'Regresar', objectives_path %>
      </div>
  </div> 

  
</div>