config/routes.rb
Rails.application.routes.draw do
  
  
  root 'pages#index'
  get '/mision-vision', to: "pages#mision_vision"
  get '/valores', to: "pages#valores"
  get '/organigrama', to: "pages#organigrama"
  get '/macroproceso', to: "pages#macroproceso"
  get '/cadena-valor', to: "pages#cadena"
  get '/fuerzas-porter', to: "pages#fuerzas"
  get '/factores-internos', to: "pages#factor_interno"
  get '/factores-externos', to: "pages#factor_externo"
  get '/matriz-foda', to: "pages#matriz_foda"
  get '/mapa-estrategico', to: "pages#mapa_estrategico"
  get '/indicador-datos', to: "pages#indicador_datos"
  get '/indicador-maestro', to: "pages#indicador_maestro"
  get '/indicador-resumen', to: "pages#indicador_resumen"


  devise_for :users
  resources :informations, :values, :areas, :activities, :forces, :factors, :expect => [:show] 
  resources :strategies, :expect => [:create]
  resources :perspectives, only: [:edit, :update, :new, :create]
  resources :objectives, :expect => [:show, :new, :edit]
  resources :procesos, :expect => [:update, :show] 
  resources :datos 
  resources :indicators, :fichas, :expect => [:new, :edit]
  
  get '/organigrama-empresa', to: 'informations#organigrama', as: 'organigrama_empresa'

  put '/procesos/:id', to: 'procesos#update', as: 'update_proceso'

  get '/subproceso/new/:proceso_id', to: 'subprocesos#new', as: 'new_subproceso'
  get '/subproceso/:proceso_id/edit/:id', to: 'subprocesos#edit', as: 'edit_subproceso'
  post '/subprocesos', to: 'subprocesos#create', as: 'create_subproceso'
  put '/subprocesos/:id', to: 'subprocesos#update', as: 'update_subproceso'
  delete '/subprocesos/:id', to: 'subprocesos#destroy', as: 'destroy_subproceso'
   
  get '/nueva-actividad/:area_id', to: "activities#new_actividad", as: 'actividad'
  get '/editar-actividad/:id/:area_id', to: 'activities#edit_actividad', as: 'actividad_edit'
  get '/nuevo-factor/:force_id', to: "factors#new_factor", as: 'factor_new'
  get '/editar-factor/:id/:force_id', to: 'factors#edit_factor', as: 'factor_edit'

  get '/evaluar-factor-interno', to: "evaluations#evaluar_factor_interno", as: 'evaluar_factor_interno'
  get '/edit-factor-interno/:id', to: "evaluations#edit_factor_interno", as: 'edit_factor_interno'
  put '/update-factor-interno/:id', to: 'activities#update_factor_interno', as: 'update_factor_interno'
  get '/evaluar-factor-externo', to: "evaluations#evaluar_factor_externo", as: 'evaluar_factor_externo'
  get '/edit-factor-externo/:id', to: "evaluations#edit_factor_externo", as: 'edit_factor_externo'
  put '/update-factor-externo/:id', to: 'factors#update_factor_externo', as: 'update_factor_externo'

  get '/strategies/new/:tipo', to: 'strategies#new', as: 'strategy_new'

  get '/nuevo-objective/:perspective_id', to: "objectives#new", as: 'objective_new'
  get '/editar-objective/:id/:perspective_id', to: 'objectives#edit', as: 'objective_edit'

  get '/mapa-estrategico-relaciones', to: "objectives#mapa", as: 'mapa_estrategico_relaciones'

  get '/nuevo-indicador/:objective_id', to: "indicators#new", as: 'indicator_new'
  get '/editar-indicador/:id/:objective_id', to: 'indicators#edit', as: 'indicator_edit'
  
  get '/nuevo-dato/:indicator_id', to: "datos#new", as: 'dato_new'
  get '/editar-dato/:id/:indicator_id', to: 'datos#edit', as: 'dato_edit'

  get '/nuevo-ficha/:indicator_id', to: "fichas#new", as: 'ficha_new'
  get '/editar-ficha/:id/:indicator_id', to: 'fichas#edit', as: 'ficha_edit'
  
  get '/maestro', to: 'maestro#index', as: 'maestro'
  get '/resumen', to: 'maestro#resumen', as: 'resumen'

end

app/models/information.rb
# == Schema Information
#
# Table name: information
#
#  id           :bigint(8)        not null, primary key
#  macroproceso :string(255)
#  mission      :text(65535)
#  name         :string(255)
#  vision       :text(65535)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Information < ApplicationRecord
    validates :name, :mission, :vision, :macroproceso, presence: true, length: {minimum: 5}
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_information, only: [:show, :edit, :update, :destroy]

  # GET /info
  # GET /info.json
  def index
    @informations = Information.all
  end

  # GET /info/1
  # GET /info/1.json
  def show
  end

  # GET /info/new
  def new
    @information = Information.new
  end

  # GET /info/1/edit
  def edit
  end

  # POST /info
  # POST /info.json
  def create
    @information = Information.new(information_params)

    respond_to do |format|
      if @information.save
        format.html { redirect_to informations_url, notice: 'La információn fue creada con exitó.' }
        format.json { redirect_to @information, status: :created, location: @information }
      else
        format.html { render :new }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /info/1
  # PATCH/PUT /info/1.json
  def update
    respond_to do |format|
      if @information.update(information_params)
        format.html { redirect_to informations_url, notice: 'La információn fue editada con exitó.' }
        format.json { redirect_to @information, status: :ok, location: @information }
      else
        format.html { render :edit }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /info/1
  # DELETE /info/1.json
  def destroy
    @information.destroy
    respond_to do |format|
      format.html { redirect_to informations_url, notice: 'La információn fue eliminada con exitó.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_information
      @information = Information.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def information_params
      params.require(:information).permit(:name, :mission, :vision, :macroproceso)
    end
end

app/views/informations/_form.html.erb
<%= form_with(model: information, url: informations_path, local: true) do |form| %>
  <% if information.errors.any? %>
    <div class="message is-danger">
      <h2 class="title is-5"><%= pluralize(information.errors.count, "error") %> al realizar está operación:</h2>
      <div class="message-body">
        <ul>
          <% information.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "label is-normal" %>
    <div class="control"> 
      <%= form.text_field :name, class: "input is-info" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :macroproceso, class: "label is-normal" %>
    <div class="control"> 
      <%= form.text_field :macroproceso, class: "input is-info" %>
    </div>
  </div> 

  <div class="field">
    <%= form.label :mission, class: "label is-normal" %>
    <div class="control"> 
      <%= form.text_area :mission, class: "textarea is-info" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :vision, class: "label is-normal" %>
    <div class="control"> 
      <%= form.text_area :vision, class: "textarea is-info" %>
    </div>
  </div>

  <div class="actifield is-grouped margin-small-topons">
    <%= form.submit "Guardar", class: "button is-primary" %>
  </div>
<% end %>

app/views/informations/edit.html.erb
<% @title = "Editar información" %>
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li> <%= link_to  "Información de la org.", informations_path %></li>
    <li class="is-active">      
      <a href="#" aria-current="page">Editar información</a>
    </li>
  </ul>
</nav>


<div class="columns">
  <div class="column is-half is-offset-one-quarter">
      <div class="card margin-small">
        <div class="card-content">
          <p class="title is-4 has-text-centered">Editar información</p>
          <p class="subtitle is-6 has-text-centered">Editar la información de la organización.</p>
                      
          <%= render 'form', information: @information %>

            <%= link_to 'Regresar', informations_path %>
      </div>
  </div> 

  
</div>

app/views/informations/index.html.erb
<% @title = "Información de la empresa" %>
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li> <%= link_to  "Dashboard", root_path %></li>
    <li class="is-active">      
      <a href="#" aria-current="page">Nosotros Somos</a>
    </li>
  </ul>
</nav>


<div class="columns">
  <div class="column">
      <div class="card margin-small shadow-cm">
        <div class="card-content">
          <p class="title is-4 has-text-centered">Información</p>
          <p class="subtitle is-6 has-text-centered">Información de la organización.</p>
                      
          <table class="table is-fullwidth">
            <thead>
              <tr>
                <th>Nombre</th>
                <th>Misión</th>
                <th>Visión</th>
                <th>Macroproceso</th>
                <th colspan="2">Acciones</th>
              </tr>
            </thead>

            <tbody>
              <% @informations.each do |information| %>
                <tr>
                  <td><%= information.name %></td>
                  <td><%= information.mission %></td>    
                  <td><%= information.vision %></td>    
                  <td><%= information.macroproceso %></td>                      
                  <td>
                    <span data-label="<%= t('.edit_link') %>" class="is-black is-top is-medium tooltip">
                      <%= link_to(edit_information_path(information), html_options =  {class: "button is-info"}) do %>
                        <span class="icon">
                          <i class="mdi mdi-square-edit-outline"></i>
                        </span>
                      <% end %>
                    </span>
                  </td>
                  <td>
                    <span data-label="<%= t('.remove_link') %>" class="is-black is-top is-medium tooltip">
                      <%= link_to information, method: :delete, data: { confirm: '¿Estás seguro de eliminar el registro?' }, class: "button is-danger" do %>
                        <span class="icon">
                          <i class="mdi mdi-delete"></i>
                        </span>
                      <% end %>
                    </span>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>

          

          <%= link_to new_information_path, class: "button is-success" do %>
              <span class="icon">
                <i class="mdi mdi-library-plus"></i>
              </span>
              <span> <%= t('.new_link') %> </span>
          <% end %>
      </div>
  </div> 

  
</div>

app/views/informations/new.html.erb
<% @title = "Agregar información de la org." %>
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li> <%= link_to  "información de la org.", informations_path %></li>
    <li class="is-active">      
      <a href="#" aria-current="page">Agregar información de la org.</a>
    </li>
  </ul>
</nav>


<div class="columns">
  <div class="column is-half is-offset-one-quarter">
      <div class="card margin-small">
        <div class="card-content">
          <p class="title is-4 has-text-centered">Agregar información de la org.</p>
          <p class="subtitle is-6 has-text-centered">Nueva información de la organización.</p>
                      
          <%= render 'form', information: @information %>

            <%= link_to 'Regresar', informations_path %>
      </div>
  </div> 

  
</div>

app/views/informations/organigrama.html.erb
<% @title = "Organigrama" %>
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li> <%= link_to  "Dashboard", root_path %></li>
    <li class="is-active">      
      <a href="#" aria-current="page">Organigrama</a>
    </li>
  </ul>
</nav>


<div class="columns">
  <div class="column">
      <div class="card margin-small shadow-cm">
        <div class="card-content">
          <p class="title is-4 has-text-centered">Organigrama</p>
          <p class="subtitle is-6 has-text-centered">Organigrama de la organización.</p>
          
          <%= image_tag  "organigrama.png", class: "width-full height-full" %>
          

         
      </div>
  </div> 

  
</div>



app/views/informations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @mission.title %>
</p>

<%= link_to 'Edit', edit_mission_path(@mission) %> |
<%= link_to 'Back', missions_path %>