config/routes.rb
Rails.application.routes.draw do
  
  
  root 'pages#index'
  get '/mision-vision', to: "pages#mision_vision"
  get '/valores', to: "pages#valores"
  get '/organigrama', to: "pages#organigrama"
  get '/macroproceso', to: "pages#macroproceso"
  get '/cadena-valor', to: "pages#cadena"
  get '/fuerzas-porter', to: "pages#fuerzas"
  get '/factores-internos', to: "pages#factor_interno"
  get '/factores-externos', to: "pages#factor_externo"
  get '/matriz-foda', to: "pages#matriz_foda"
  get '/mapa-estrategico', to: "pages#mapa_estrategico"
  get '/indicador-datos', to: "pages#indicador_datos"
  get '/indicador-maestro', to: "pages#indicador_maestro"
  get '/indicador-resumen', to: "pages#indicador_resumen"


  devise_for :users
  resources :informations, :values, :areas, :activities, :forces, :factors, :expect => [:show] 
  resources :strategies, :expect => [:create]
  resources :perspectives, only: [:edit, :update, :new, :create]
  resources :objectives, :expect => [:show, :new, :edit]
  resources :procesos, :expect => [:update, :show] 
  resources :datos 
  resources :indicators, :fichas, :expect => [:new, :edit]
  
  get '/organigrama-empresa', to: 'informations#organigrama', as: 'organigrama_empresa'

  put '/procesos/:id', to: 'procesos#update', as: 'update_proceso'

  get '/subproceso/new/:proceso_id', to: 'subprocesos#new', as: 'new_subproceso'
  get '/subproceso/:proceso_id/edit/:id', to: 'subprocesos#edit', as: 'edit_subproceso'
  post '/subprocesos', to: 'subprocesos#create', as: 'create_subproceso'
  put '/subprocesos/:id', to: 'subprocesos#update', as: 'update_subproceso'
  delete '/subprocesos/:id', to: 'subprocesos#destroy', as: 'destroy_subproceso'
   
  get '/nueva-actividad/:area_id', to: "activities#new_actividad", as: 'actividad'
  get '/editar-actividad/:id/:area_id', to: 'activities#edit_actividad', as: 'actividad_edit'
  get '/nuevo-factor/:force_id', to: "factors#new_factor", as: 'factor_new'
  get '/editar-factor/:id/:force_id', to: 'factors#edit_factor', as: 'factor_edit'

  get '/evaluar-factor-interno', to: "evaluations#evaluar_factor_interno", as: 'evaluar_factor_interno'
  get '/edit-factor-interno/:id', to: "evaluations#edit_factor_interno", as: 'edit_factor_interno'
  put '/update-factor-interno/:id', to: 'activities#update_factor_interno', as: 'update_factor_interno'
  get '/evaluar-factor-externo', to: "evaluations#evaluar_factor_externo", as: 'evaluar_factor_externo'
  get '/edit-factor-externo/:id', to: "evaluations#edit_factor_externo", as: 'edit_factor_externo'
  put '/update-factor-externo/:id', to: 'factors#update_factor_externo', as: 'update_factor_externo'

  get '/strategies/new/:tipo', to: 'strategies#new', as: 'strategy_new'

  get '/nuevo-objective/:perspective_id', to: "objectives#new", as: 'objective_new'
  get '/editar-objective/:id/:perspective_id', to: 'objectives#edit', as: 'objective_edit'

  get '/mapa-estrategico-relaciones', to: "objectives#mapa", as: 'mapa_estrategico_relaciones'

  get '/nuevo-indicador/:objective_id', to: "indicators#new", as: 'indicator_new'
  get '/editar-indicador/:id/:objective_id', to: 'indicators#edit', as: 'indicator_edit'
  
  get '/nuevo-dato/:indicator_id', to: "datos#new", as: 'dato_new'
  get '/editar-dato/:id/:indicator_id', to: 'datos#edit', as: 'dato_edit'

  get '/nuevo-ficha/:indicator_id', to: "fichas#new", as: 'ficha_new'
  get '/editar-ficha/:id/:indicator_id', to: 'fichas#edit', as: 'ficha_edit'
  
  get '/maestro', to: 'maestro#index', as: 'maestro'
  get '/resumen', to: 'maestro#resumen', as: 'resumen'

end

app/controllers/procesos_controller.rb
class ProcesosController < ApplicationController
    before_action :authenticate_user!
    before_action :set_processing, only: [:show, :edit, :update, :destroy]

    # GET /info
    # GET /info.json
    def index
        @informations = Information.all
        @processings = Processing.all
    end

    # GET /info/1
    # GET /info/1.json
    def show
    end

    # GET /info/new
    def new
        @processing = Processing.new
    end

    # GET /info/1/edit
    def edit
    end

    # POST /info
    # POST /info.json
    def create
        @processing = Processing.new(processing_params)

        respond_to do |format|
            if @processing.save
                format.html { redirect_to procesos_url, notice: 'El proceso fue creada con exitó.' }
                format.json { redirect_to @processing, status: :created, location: @processing }
            else
                format.html { render :new }
                format.json { render json: @processing.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /info/1
    # PATCH/PUT /info/1.json
    def update
        respond_to do |format|
            if @processing.update(processing_params)
                format.html { redirect_to procesos_url, notice: 'El proceso fue editada con exitó.' }
                format.json { redirect_to @processing, status: :ok, location: @processing }
            else
                format.html { render :edit }
                format.json { render json: @processing.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /info/1
    # DELETE /info/1.json
    def destroy
        @processing.destroy
        respond_to do |format|
            format.html { redirect_to procesos_url, notice: 'El proceso fue eliminada con exitó.' }
            format.json { head :no_content }
        end
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_processing
            @processing = Processing.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def processing_params
            params.require(:processing).permit(:title)
        end
end

app/views/procesos/edit.html.erb
<% @title = "Editar Proceso" %>
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li> <%= link_to  "Proceso", procesos_path %></li>
    <li class="is-active">      
      <a href="#" aria-current="page">Editar Proceso</a>
    </li>
  </ul>
</nav>


<div class="columns">
  <div class="column is-half is-offset-one-quarter">
      <div class="card margin-small">
        <div class="card-content">
          <p class="title is-4 has-text-centered">Editar Proceso</p>
          <p class="subtitle is-6 has-text-centered">Editar el proceso de la organización.</p>
                      
            <%= form_with(model: @processing, url: update_proceso_path(@processing), method: 'PUT', local: true) do |form| %>
              <% if @processing.errors.any? %>
                <div class="message is-danger">
                  <h2 class="title is-5"><%= pluralize(@processing.errors.count, "error") %> al realizar la operación:</h2>
                  <div class="message-body">
                    <ul>
                      <% @processing.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                    </ul>
                  </div>
                </div>
              <% end %>

              <div class="field">
                <%= form.label :title, class: "label is-normal" %>
                <div class="control"> 
                  <%= form.text_field :title, class: "input is-info" %>
                </div>
              </div>

              <div class="actifield is-grouped margin-small-topons">
                <%= form.submit "Guardar", class: "button is-primary" %>
              </div>
            <% end %>

            <%= link_to 'Regresar', procesos_path %>
        </div>
      </div>

  </div>
</div>

app/views/procesos/index.html.erb
<% @title = "Macroproceso" %>

<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li> <%= link_to  "Dashboard", root_path %></li>
    <li class="is-active">      
      <a href="#" aria-current="page">El Macroproceso</a>
    </li>
  </ul>
</nav>


<div class="columns">
  <div class="column">
      <div class="card margin-small shadow-cm">
        <div class="card-content">

          <div class="columns is-middle">
            <div class="column is-4">
              <p class="title is-4 has-text-centered">El Macroproceso</p>
            </div>
            <div class="column">
                <div class="notification is-primary has-text-centered">
                  <% @informations.each do |information| %>
                      <strong class="subtitle is-5">" <%= information.macroproceso %> "</strong>
                  <% end %>            
                </div>   
            </div>
          </div>  
         
          <div class="columns">
            <div class="column">
                <p class="subtitle is-6 has-text-left">Los procesos de la organización.</p>
            </div>
            <div class="column is-2 has-text-rigth">
              <%= link_to  new_proceso_path, class: "button is-success"  do %>
                  <span class="icon">
                    <i class="mdi mdi-plus is-24px"></i>
                  </span> 
                  <%= t('.new_proceso_link') %>                
              <% end %>
            </div>
          </div>


              
          <h3 class="title is-5">
            Procesos <span class="icon"> <i class="mdi mdi-arrow-down"></i></span>
          </h3> 
          <div class="shadow-cm padding-small-all">
            <% @processings.each do |proceso| %>
              <div class="columns ">
                <div class="column is-8 has-background-primary has-text-white">
                  <div class="has-text-weight-bold">
                    <%= proceso.title %>
                  </div>
                </div>

                <div class="column is-2 has-text-right has-background-primary has-text-white">
                  <span data-label="<%= t('.edit_proceso_link') %>" class="is-black is-top is-medium tooltip">
                    <%= link_to edit_proceso_path(proceso), class: "button is-info" do %>
                        <span class="icon">
                          <i class="mdi mdi-update"></i>
                        </span>
                    <% end %>
                  </span>
                  <span data-label="<%= t('.remove_proceso_link') %>" class="is-black is-top is-medium tooltip">
                    <%= link_to procesos_path(proceso), method: :delete, class: "button is-danger", data: {confirm: "¿Está seguro de eliminar el proceso?"} do %>
                        <span class="icon">
                          <i class="mdi mdi-close"></i>
                        </span>
                    <% end %>
                  </span>
                </div>

                <div class="column has-background-grey has-text-white">
                  <%= link_to new_subproceso_path(proceso.id), class: "button" do %>
                    <span class="icon">
                      <i class="mdi mdi-library-plus"></i>
                    </span>
                    <span><%= t('.new_link') %> </span>
                  <% end %>
                </div>
              </div>


              <% proceso.sub_processes.each do |subprocess| %>
                <div class="columns">

                    <div class="column is-10">
                      <%= subprocess.title %>
                    </div>

                    <div class="column">
                      <span data-label="<%= t('.edit_link') %>" class="is-black is-top is-medium tooltip">
                        <%= link_to edit_subproceso_path(proceso.id,subprocess), class: "button is-info" do %>
                          <span class="icon">
                            <i class="mdi mdi-update"></i>
                          </span>
                        <% end %>
                      </span>
                      <span data-label="<%= t('.remove_link') %>" class="is-black is-top is-medium tooltip">
                        <%= link_to destroy_subproceso_path(subprocess), method: :delete,  class: "button is-danger", :data => {confirm: '¿Está seguro de eliminar el subproceso?'} do %>
                          <span class="icon">
                            <i class="mdi mdi-close"></i>
                          </span>
                        <% end %>
                      </span>
                    </div>
                </div>
              <% end %>
            <% end %>

          </div>

          <h3 class="title is-5">
            Sub Procesos <span class="icon"> <i class="mdi mdi-arrow-up"></i></span>
          </h3> 
        </div>
      </div>
  </div>  
</div>

app/views/procesos/new.html.erb
<% @title = 'Agregar proceso' %>
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li> <%= link_to  "Procesos", procesos_path %></li>
    <li class="is-active">      
      <a href="#" aria-current="page">Agregar proceso</a>
    </li>
  </ul>
</nav>


<div class="columns">
  <div class="column is-half is-offset-one-quarter">
      <div class="card margin-small">
        <div class="card-content">
          <p class="title is-4 has-text-centered">Agregar proceso</p>
          <p class="subtitle is-6 has-text-centered">Nuevo proceso de la organización.</p>
                      
          <%= form_with(model: @processing, url: procesos_path, local: true) do |form| %>
            <% if @processing.errors.any? %>
              <div class="message is-danger">
                <h2 class="title is-5"><%= pluralize(@processing.errors.count, "error") %> al realizar la operación:</h2>
                <div class="message-body">
                  <ul>
                    <% @processing.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              </div>
            <% end %>

            <div class="field">
              <%= form.label :title, class: "label is-normal" %>
              <div class="control"> 
                <%= form.text_field :title, class: "input is-info" %>
              </div>
            </div>

            <div class="actifield is-grouped margin-small-topons">
              <%= form.submit "Guardar", class: "button is-primary" %>
            </div>
          <% end %>

          <%= link_to 'Regresar', procesos_path %>
      </div>
  </div> 

  </div>
</div>