config/routes.rb
Rails.application.routes.draw do
  
  
  root 'pages#index'
  get '/mision-vision', to: "pages#mision_vision"
  get '/valores', to: "pages#valores"
  get '/organigrama', to: "pages#organigrama"
  get '/macroproceso', to: "pages#macroproceso"
  get '/cadena-valor', to: "pages#cadena"
  get '/fuerzas-porter', to: "pages#fuerzas"
  get '/factores-internos', to: "pages#factor_interno"
  get '/factores-externos', to: "pages#factor_externo"
  get '/matriz-foda', to: "pages#matriz_foda"
  get '/mapa-estrategico', to: "pages#mapa_estrategico"
  get '/indicador-datos', to: "pages#indicador_datos"
  get '/indicador-maestro', to: "pages#indicador_maestro"
  get '/indicador-resumen', to: "pages#indicador_resumen"


  devise_for :users
  resources :informations, :values, :areas, :activities, :forces, :factors, :expect => [:show] 
  resources :strategies, :expect => [:create]
  resources :perspectives, only: [:edit, :update, :new, :create]
  resources :objectives, :expect => [:show, :new, :edit]
  resources :procesos, :expect => [:update, :show] 
  resources :datos 
  resources :indicators, :fichas, :expect => [:new, :edit]
  
  get '/organigrama-empresa', to: 'informations#organigrama', as: 'organigrama_empresa'

  put '/procesos/:id', to: 'procesos#update', as: 'update_proceso'

  get '/subproceso/new/:proceso_id', to: 'subprocesos#new', as: 'new_subproceso'
  get '/subproceso/:proceso_id/edit/:id', to: 'subprocesos#edit', as: 'edit_subproceso'
  post '/subprocesos', to: 'subprocesos#create', as: 'create_subproceso'
  put '/subprocesos/:id', to: 'subprocesos#update', as: 'update_subproceso'
  delete '/subprocesos/:id', to: 'subprocesos#destroy', as: 'destroy_subproceso'
   
  get '/nueva-actividad/:area_id', to: "activities#new_actividad", as: 'actividad'
  get '/editar-actividad/:id/:area_id', to: 'activities#edit_actividad', as: 'actividad_edit'
  get '/nuevo-factor/:force_id', to: "factors#new_factor", as: 'factor_new'
  get '/editar-factor/:id/:force_id', to: 'factors#edit_factor', as: 'factor_edit'

  get '/evaluar-factor-interno', to: "evaluations#evaluar_factor_interno", as: 'evaluar_factor_interno'
  get '/edit-factor-interno/:id', to: "evaluations#edit_factor_interno", as: 'edit_factor_interno'
  put '/update-factor-interno/:id', to: 'activities#update_factor_interno', as: 'update_factor_interno'
  get '/evaluar-factor-externo', to: "evaluations#evaluar_factor_externo", as: 'evaluar_factor_externo'
  get '/edit-factor-externo/:id', to: "evaluations#edit_factor_externo", as: 'edit_factor_externo'
  put '/update-factor-externo/:id', to: 'factors#update_factor_externo', as: 'update_factor_externo'

  get '/strategies/new/:tipo', to: 'strategies#new', as: 'strategy_new'

  get '/nuevo-objective/:perspective_id', to: "objectives#new", as: 'objective_new'
  get '/editar-objective/:id/:perspective_id', to: 'objectives#edit', as: 'objective_edit'

  get '/mapa-estrategico-relaciones', to: "objectives#mapa", as: 'mapa_estrategico_relaciones'

  get '/nuevo-indicador/:objective_id', to: "indicators#new", as: 'indicator_new'
  get '/editar-indicador/:id/:objective_id', to: 'indicators#edit', as: 'indicator_edit'
  
  get '/nuevo-dato/:indicator_id', to: "datos#new", as: 'dato_new'
  get '/editar-dato/:id/:indicator_id', to: 'datos#edit', as: 'dato_edit'

  get '/nuevo-ficha/:indicator_id', to: "fichas#new", as: 'ficha_new'
  get '/editar-ficha/:id/:indicator_id', to: 'fichas#edit', as: 'ficha_edit'
  
  get '/maestro', to: 'maestro#index', as: 'maestro'
  get '/resumen', to: 'maestro#resumen', as: 'resumen'

end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id             :bigint(8)        not null, primary key
#  alta           :integer          default(0)
#  baja           :integer          default(0)
#  bueno          :integer          default(0)
#  deficiente     :integer          default(0)
#  media          :integer          default(0)
#  muy_bueno      :integer          default(0)
#  muy_deficiente :integer          default(0)
#  name           :text(65535)
#  valor          :integer          default(0)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  area_id        :bigint(8)
#
# Indexes
#
#  index_activities_on_area_id  (area_id)
#
# Foreign Keys
#
#  fk_rails_...  (area_id => areas.id)
#

class Activity < ApplicationRecord
  validates :name, presence: true

  belongs_to :area
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
    before_action :authenticate_user!
    before_action :find_activity, only: [:edit, :update, :show, :destroy, :edit_actividad, :update_factor_interno]

    
    def index
        @activities = Activity.all
        @areas = Area.all
    end

    
    def show
    end

    
    def new
        @area_id = params[:area_id]
        @activity = Activity.new
    end

    def new_actividad
        @area_id = params[:area_id]
        @activity = Activity.new
    end

    def edit_actividad
        @area_id = params[:area_id]
    end
    
    def edit
    end

    
    def create
        @activity = Activity.new(activity_params)

        respond_to do |format|
        if @activity.save
            format.html { redirect_to activities_url, notice: 'El área fue creada con exitó.' }
            format.json { redirect_to @activity, status: :created, location: @activity }
        else
            format.html { render :new }
            format.json { render json: @activity.errors, status: :unprocessable_entity }
        end
        end
    end

    
    def update
        respond_to do |format|
        if @activity.update(activity_params)
            format.html { redirect_to activities_url, notice: 'El área fue editada con exitó.' }
            format.json { redirect_to @activity, status: :ok, location: @activity }
        else
            format.html { render :edit }
            format.json { render json: @activity.errors, status: :unprocessable_entity }
        end
        end
    end

    
    def destroy
        @activity.destroy
        respond_to do |format|
        format.html { redirect_to activities_url, notice: 'El área fue eliminada con exitó.' }
        format.json { head :no_content }
        end
    end

    def update_factor_interno
        @activity[:alta] = params[:activity][:alta]
        @activity[:media] = params[:activity][:media]
        @activity[:baja] = params[:activity][:baja]
        @activity[:muy_bueno] = params[:activity][:muy_bueno]
        @activity[:bueno] = params[:activity][:bueno]
        @activity[:deficiente] = params[:activity][:deficiente]
        @activity[:muy_deficiente] = params[:activity][:muy_deficiente]
        @valor ||= (@activity[:alta] + @activity[:media] + @activity[:baja]) * (@activity[:muy_bueno] + @activity[:bueno] + @activity[:deficiente] + @activity[:muy_deficiente])
        @activity[:valor] = @valor

        respond_to do |format|
            if @activity.save
                if @activity[:valor] > 0
                    @total = Strength.count
                    @fortaleza = Strength.new
                    @fortaleza[:slug] = "F#{@total + 1}"
                    @fortaleza[:content] = @activity[:name]
                    @fortaleza.save

                    format.html { redirect_to evaluar_factor_interno_url, notice: 'La evaluación se hizo con exitó.' }
                    format.json { redirect_to @activity, status: :ok, location: @activity }
                else
                    @total = Weakness.count
                    @debilidad = Weakness.new
                    @debilidad[:slug] = "D#{@total + 1}"
                    @debilidad[:content] = @activity[:name]
                    @debilidad.save

                    format.html { redirect_to evaluar_factor_interno_url, notice: 'La evaluación se hizo con exitó.' }
                    format.json { redirect_to @activity, status: :ok, location: @activity }
                end                
            else
                format.html { render :edit }
                format.json { render json: @activity.errors, status: :unprocessable_entity }
            end
        end
        #render json: params[:activity][:alta]
        #@valor ||= (@activity[:alta] + @activity[:media] + @activity[:baja]) * (@activity[:muy_bueno] + @activity[:bueno] + @activity[:deficiente] + @activity[:muy_deficiente])
        #render json: activity_params
        
    end

    private 
        def activity_params
            params.require(:activity).permit(:name, :area_id, :alta, :media, :baja, :muy_bueno, :bueno, :deficiente, :muy_deficiente, :valor)
        end

        def find_activity
            @activity = Activity.find(params[:id])
        end
        
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div class="message is-danger">
      <h2 class="title is-5 has-text-danger"><%= pluralize(activity.errors.count, "error") %> al realizar la operación:</h2>
      <div class="message-body">
        <ul>
          <% activity.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <%= form.hidden_field :area_id, value: @area_id %>
  <div class="field">
    <%= form.label :name, class: "label is-normal" %>
    <div class="control"> 
      <%= form.text_area :name, class: "textarea is-info" %>
    </div>
  </div>

  <div class="field is-grouped margin-small-topons">
    <%= form.submit "Guardar", class: "button is-primary" %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li> <%= link_to  "Actividades", activities_path %></li>
    <li class="is-active">      
      <a href="#" aria-current="page">Editar Actividad</a>
    </li>
  </ul>
</nav>


<div class="columns">
  <div class="column is-half is-offset-one-quarter">
      <div class="card margin-small">
        <div class="card-content">
          <p class="title is-4 has-text-centered">Editar Actividad</p>
          <p class="subtitle is-6 has-text-centered">Editar la Actividad de la organización.</p>
                      
          <%= render 'form', activity: @activity %>

            <%= link_to 'Regresar', activities_path %>
      </div>
  </div> 

  
</div>

app/views/activities/edit_actividad.html.erb
<% @title = "Editar Actividad" %>
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li> <%= link_to  "Actividades", activities_path %></li>
    <li class="is-active">      
      <a href="#" aria-current="page">Editar Actividad</a>
    </li>
  </ul>
</nav>


<div class="columns">
  <div class="column is-half is-offset-one-quarter">
      <div class="card margin-small">
        <div class="card-content">
          <p class="title is-4 has-text-centered">Editar Actividad</p>
          <p class="subtitle is-6 has-text-centered">Modificar actividad de la organización.</p>
                      
          <%= render 'form', activity: @activity %>

            <%= link_to 'Regresar', activities_path %>
        </div>
      </div>

  </div>
</div>

app/views/activities/index.html.erb
<% @title = "Cadena de valor" %>
<div class="columns">
  <div class="column">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li> <%= link_to  "Dashboard", root_path %></li>
        <li class="is-active">      
          <a href="#" aria-current="page">Cadena de valor</a>
        </li>
      </ul>
    </nav>
  </div>

  <div class="column is-flex-row-end">
    <%= link_to evaluar_factor_interno_path, class: "button is-info" do %>
      <p> Evaluar Factores Internos </p>
      <span class="icon">
        <i class="mdi mdi-arrow-right"></i>
      </span>
    <% end %>
  </div>
</div>


<div class="columns">
  <div class="column">
      <div class="card margin-small shadow-cm">
        <div class="card-content">
          <p class="subtitle has-text-centered">Las áreas y actividades de la organización.</p>
          <div class="is-between">
            <p class="title is-4">Cadena de valor</p>
            <%= link_to new_area_path, class: "button is-success" do %>
                <span class="icon">
                  <i class="mdi mdi-library-plus"></i>
                </span>
                <span><%= t('.new_area_link') %> </span>
            <% end %>
          </div>

          <div class="shadow-cm padding-small-all">
            <% @areas.each do |area| %>
              <div class="columns ">
                <div class="column is-8 has-background-primary has-text-white">
                  <div class="has-text-weight-bold">
                    <%= area.name %>
                  </div>
                </div>

                <div class="column is-2 has-text-right has-background-primary has-text-white">
                  <span data-label="<%= t('.edit_area_link') %>" class="is-black is-top is-medium tooltip">
                    <%= link_to edit_area_path(area), class: "button is-info" do %>
                        <span class="icon">
                          <i class="mdi mdi-update"></i>
                        </span>
                    <% end %>
                  </span>
                  <span data-label="<%= t('.remove_area_link') %>" class="is-black is-top is-medium tooltip">
                    <%= link_to area, method: :delete, class: "button is-danger", data: {confirm: "¿Está seguro de eliminar el área?"} do %>
                        <span class="icon">
                          <i class="mdi mdi-close"></i>
                        </span>
                    <% end %>
                  </span>
                </div>

                <div class="column has-background-grey has-text-white">
                  <%= link_to actividad_path(area), class: "button" do %>
                    <span class="icon">
                      <i class="mdi mdi-library-plus"></i>
                    </span>
                    <span><%= t('.new_link') %> </span>
                  <% end %>
                </div>
              </div>


              <% area.activities.each do |actividad| %>
                <div class="columns">

                    <div class="column is-10">
                      <%= actividad.name %>
                    </div>

                    <div class="column">
                      <span data-label="<%= t('.edit_link') %>" class="is-black is-top is-medium tooltip">
                        <%= link_to actividad_edit_path(actividad,area), class: "button is-info" do %>
                          <span class="icon">
                            <i class="mdi mdi-update"></i>
                          </span>
                        <% end %>
                      </span>
                      <span data-label="<%= t('.remove_link') %>" class="is-black is-top is-medium tooltip">
                        <%= link_to activity_url(actividad), method: :delete,  class: "button is-danger", :data => {confirm: '¿Está seguro de eliminar la actividad?'} do %>
                          <span class="icon">
                            <i class="mdi mdi-close"></i>
                          </span>
                        <% end %>
                      </span>
                    </div>
                </div>
              <% end %>
            <% end %>

          </div>

          


        </div>
      </div>

  </div>
</div>

app/views/activities/new.html.erb
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li> <%= link_to  "Actividades", activities_path %></li>
    <li class="is-active">      
      <a href="#" aria-current="page">Agregar Actividad</a>
    </li>
  </ul>
</nav>


<div class="columns">
  <div class="column is-half is-offset-one-quarter">
      <div class="card margin-small">
        <div class="card-content">
          <p class="title is-4 has-text-centered">Agregar Actividad</p>
          <p class="subtitle is-6 has-text-centered">Nueva actividad de la organización.</p>
                      
          <%= render 'form', activity: @activity %>

            <%= link_to 'Regresar', activities_path %>
      </div>
  </div> 

  
</div>

app/views/activities/new_actividad.html.erb
<% @title = "Agregar Actividad" %>
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li> <%= link_to  "Actividades", activities_path %></li>
    <li class="is-active">      
      <a href="#" aria-current="page">Agregar Actividad</a>
    </li>
  </ul>
</nav>


<div class="columns">
  <div class="column is-half is-offset-one-quarter">
      <div class="card margin-small">
        <div class="card-content">
          <p class="title is-4 has-text-centered">Agregar Actividad</p>
          <p class="subtitle is-6 has-text-centered">Nueva actividad de la organización.</p>
                      
          <%= render 'form', activity: @activity %>

            <%= link_to 'Regresar', activities_path %>
        </div>
      </div>

  </div>
</div>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @activity.name %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>